//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFC_Analyzer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFC_Analyzer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute URI Type.
        /// </summary>
        public static string AbsUriType {
            get {
                return ResourceManager.GetString("AbsUriType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Name:.
        /// </summary>
        public static string AddlNameHdr {
            get {
                return ResourceManager.GetString("AddlNameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Names:.
        /// </summary>
        public static string AddlNamesHdr {
            get {
                return ResourceManager.GetString("AddlNamesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string AddressHdr {
            get {
                return ResourceManager.GetString("AddressHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary:.
        /// </summary>
        public static string AnnivHdr {
            get {
                return ResourceManager.GetString("AnnivHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Args:.
        /// </summary>
        public static string ArgsHdr {
            get {
                return ResourceManager.GetString("ArgsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach your NFC Reader..
        /// </summary>
        public static string AttachNfcReader {
            get {
                return ResourceManager.GetString("AttachNfcReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string BdayHdr {
            get {
                return ResourceManager.GetString("BdayHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy Time URI:.
        /// </summary>
        public static string BusyTimeUriHdr {
            get {
                return ResourceManager.GetString("BusyTimeUriHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar URI:.
        /// </summary>
        public static string CalUriHdr {
            get {
                return ResourceManager.GetString("CalUriHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar User Address URI:.
        /// </summary>
        public static string CalUserAddrUriHdr {
            get {
                return ResourceManager.GetString("CalUserAddrUriHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string CellPre {
            get {
                return ResourceManager.GetString("CellPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunked Format.
        /// </summary>
        public static string ChunkedFormatItem {
            get {
                return ResourceManager.GetString("ChunkedFormatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localities (Cities): .
        /// </summary>
        public static string CitiesHdr {
            get {
                return ResourceManager.GetString("CitiesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality (City): .
        /// </summary>
        public static string CityHdr {
            get {
                return ResourceManager.GetString("CityHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Initialize button when done..
        /// </summary>
        public static string ClickInitButton {
            get {
                return ResourceManager.GetString("ClickInitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries:.
        /// </summary>
        public static string CountriesHdr {
            get {
                return ResourceManager.GetString("CountriesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string CountryHdr {
            get {
                return ResourceManager.GetString("CountryHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client PID Map:.
        /// </summary>
        public static string CpidMapHdr {
            get {
                return ResourceManager.GetString("CpidMapHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailHdr {
            get {
                return ResourceManager.GetString("EmailHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        public static string EncodingHdr {
            get {
                return ResourceManager.GetString("EncodingHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Addresses:.
        /// </summary>
        public static string ExtAddressesHdr {
            get {
                return ResourceManager.GetString("ExtAddressesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Address:.
        /// </summary>
        public static string ExtAddressHdr {
            get {
                return ResourceManager.GetString("ExtAddressHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Forum External Type.
        /// </summary>
        public static string ExternalType {
            get {
                return ResourceManager.GetString("ExternalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook URL:.
        /// </summary>
        public static string FacebookUrlHdr {
            get {
                return ResourceManager.GetString("FacebookUrlHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name:.
        /// </summary>
        public static string FamNameHdr {
            get {
                return ResourceManager.GetString("FamNameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Names:.
        /// </summary>
        public static string FamNamesHdr {
            get {
                return ResourceManager.GetString("FamNamesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Name:.
        /// </summary>
        public static string FormNameHdr {
            get {
                return ResourceManager.GetString("FormNameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string GenderHdr {
            get {
                return ResourceManager.GetString("GenderHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Control.
        /// </summary>
        public static string GenericCtrl {
            get {
                return ResourceManager.GetString("GenericCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocode:.
        /// </summary>
        public static string GeoCodeHdr {
            get {
                return ResourceManager.GetString("GeoCodeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name:.
        /// </summary>
        public static string GivenNameHdr {
            get {
                return ResourceManager.GetString("GivenNameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Names:.
        /// </summary>
        public static string GivenNamesHdr {
            get {
                return ResourceManager.GetString("GivenNamesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover Carrier.
        /// </summary>
        public static string HandoverCar {
            get {
                return ResourceManager.GetString("HandoverCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover Request.
        /// </summary>
        public static string HandoverReq {
            get {
                return ResourceManager.GetString("HandoverReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handover Select.
        /// </summary>
        public static string HandoverSel {
            get {
                return ResourceManager.GetString("HandoverSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Length Field is present..
        /// </summary>
        public static string HasIdLengthItem {
            get {
                return ResourceManager.GetString("HasIdLengthItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address:.
        /// </summary>
        public static string HmAdrHdr {
            get {
                return ResourceManager.GetString("HmAdrHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address:.
        /// </summary>
        public static string HomeAddrHdr {
            get {
                return ResourceManager.GetString("HomeAddrHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific Prefixes:.
        /// </summary>
        public static string HonPrefixesHdr {
            get {
                return ResourceManager.GetString("HonPrefixesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific Prefix:.
        /// </summary>
        public static string HonPrefixHdr {
            get {
                return ResourceManager.GetString("HonPrefixHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific Suffixes: .
        /// </summary>
        public static string HonSuffixesHdr {
            get {
                return ResourceManager.GetString("HonSuffixesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific Suffix: .
        /// </summary>
        public static string HonSuffixHdr {
            get {
                return ResourceManager.GetString("HonSuffixHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Length:.
        /// </summary>
        public static string IdLengthHdr {
            get {
                return ResourceManager.GetString("IdLengthHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type:.
        /// </summary>
        public static string IdTypeHdr {
            get {
                return ResourceManager.GetString("IdTypeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Messaging and Presence Protocol URI:.
        /// </summary>
        public static string ImppUriHdr {
            get {
                return ResourceManager.GetString("ImppUriHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Inet {
            get {
                return ResourceManager.GetString("Inet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Email:.
        /// </summary>
        public static string InetEmailHdr {
            get {
                return ResourceManager.GetString("InetEmailHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        public static string initButton {
            get {
                return ResourceManager.GetString("initButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageHdr {
            get {
                return ResourceManager.GetString("LanguageHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo:.
        /// </summary>
        public static string LogoHdr {
            get {
                return ResourceManager.GetString("LogoHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Record (Four byte payload length field).
        /// </summary>
        public static string LongRecordItem {
            get {
                return ResourceManager.GetString("LongRecordItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Length:.
        /// </summary>
        public static string MaxLengthHdr {
            get {
                return ResourceManager.GetString("MaxLengthHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type:.
        /// </summary>
        public static string MediaTypeHdr {
            get {
                return ResourceManager.GetString("MediaTypeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member:.
        /// </summary>
        public static string MemberHdr {
            get {
                return ResourceManager.GetString("MemberHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Begin.
        /// </summary>
        public static string MsgBeginItem {
            get {
                return ResourceManager.GetString("MsgBeginItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Bytes:.
        /// </summary>
        public static string MsgBytesHdr {
            get {
                return ResourceManager.GetString("MsgBytesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Characters:.
        /// </summary>
        public static string MsgCharHdr {
            get {
                return ResourceManager.GetString("MsgCharHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message End.
        /// </summary>
        public static string MsgEndItem {
            get {
                return ResourceManager.GetString("MsgEndItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Length:.
        /// </summary>
        public static string MsgLengthHdr {
            get {
                return ResourceManager.GetString("MsgLengthHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Received.
        /// </summary>
        public static string MsgRcvd {
            get {
                return ResourceManager.GetString("MsgRcvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text:.
        /// </summary>
        public static string MsgTextHdr {
            get {
                return ResourceManager.GetString("MsgTextHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type.
        /// </summary>
        public static string MsgType {
            get {
                return ResourceManager.GetString("MsgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type:.
        /// </summary>
        public static string MsgTypeHdr {
            get {
                return ResourceManager.GetString("MsgTypeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameHdr {
            get {
                return ResourceManager.GetString("NameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDEF Record:.
        /// </summary>
        public static string NDEFRecHdr {
            get {
                return ResourceManager.GetString("NDEFRecHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname:.
        /// </summary>
        public static string NicknameHdr {
            get {
                return ResourceManager.GetString("NicknameHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ID.
        /// </summary>
        public static string NoId {
            get {
                return ResourceManager.GetString("NoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Length Field is omitted..
        /// </summary>
        public static string NoIdLengthItem {
            get {
                return ResourceManager.GetString("NoIdLengthItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-chunked Format.
        /// </summary>
        public static string NonChunkedFormatItem {
            get {
                return ResourceManager.GetString("NonChunkedFormatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string NoteHdr {
            get {
                return ResourceManager.GetString("NoteHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization:.
        /// </summary>
        public static string OrgHdr {
            get {
                return ResourceManager.GetString("OrgHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter 1.
        /// </summary>
        public static string Param1 {
            get {
                return ResourceManager.GetString("Param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter 2.
        /// </summary>
        public static string Param2 {
            get {
                return ResourceManager.GetString("Param2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter 3.
        /// </summary>
        public static string Param3 {
            get {
                return ResourceManager.GetString("Param3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload:.
        /// </summary>
        public static string PayloadHdr {
            get {
                return ResourceManager.GetString("PayloadHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload Length:.
        /// </summary>
        public static string PayloadLengthHdr {
            get {
                return ResourceManager.GetString("PayloadLengthHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo:.
        /// </summary>
        public static string PhotoHdr {
            get {
                return ResourceManager.GetString("PhotoHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Office Boxes:.
        /// </summary>
        public static string POBoxesHdr {
            get {
                return ResourceManager.GetString("POBoxesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Office Box:.
        /// </summary>
        public static string POBoxHdr {
            get {
                return ResourceManager.GetString("POBoxHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code: .
        /// </summary>
        public static string PostalCodeHdr {
            get {
                return ResourceManager.GetString("PostalCodeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Codes: .
        /// </summary>
        public static string PostalCodesHdr {
            get {
                return ResourceManager.GetString("PostalCodesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Preferred).
        /// </summary>
        public static string PrefParam {
            get {
                return ResourceManager.GetString("PrefParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID:.
        /// </summary>
        public static string ProdIdHdr {
            get {
                return ResourceManager.GetString("ProdIdHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Analyser.
        /// </summary>
        public static string programTitle {
            get {
                return ResourceManager.GetString("programTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity device initialized..
        /// </summary>
        public static string ProxDevInit {
            get {
                return ResourceManager.GetString("ProxDevInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity device not present..
        /// </summary>
        public static string ProxDevNotPresent {
            get {
                return ResourceManager.GetString("ProxDevNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key or Authentication Certificate:.
        /// </summary>
        public static string PubKeyOrAuthCertHdr {
            get {
                return ResourceManager.GetString("PubKeyOrAuthCertHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region (e.g., State or Province):.
        /// </summary>
        public static string RegionHdr {
            get {
                return ResourceManager.GetString("RegionHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions (e.g., States or Provinces):.
        /// </summary>
        public static string RegionsHdr {
            get {
                return ResourceManager.GetString("RegionsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejected.
        /// </summary>
        public static string rejected {
            get {
                return ResourceManager.GetString("rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related:.
        /// </summary>
        public static string RelatedHdr {
            get {
                return ResourceManager.GetString("RelatedHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming from suspend ....
        /// </summary>
        public static string ResumingMsg {
            get {
                return ResourceManager.GetString("ResumingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision:.
        /// </summary>
        public static string RevHdr {
            get {
                return ResourceManager.GetString("RevHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string RoleHdr {
            get {
                return ResourceManager.GetString("RoleHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for tag..
        /// </summary>
        public static string ScanningForTag {
            get {
                return ResourceManager.GetString("ScanningForTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Record (Single byte payload length field).
        /// </summary>
        public static string ShortRecordItem {
            get {
                return ResourceManager.GetString("ShortRecordItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Sig {
            get {
                return ResourceManager.GetString("Sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Poster.
        /// </summary>
        public static string SmartPoster {
            get {
                return ResourceManager.GetString("SmartPoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound URI:.
        /// </summary>
        public static string SndUriHdr {
            get {
                return ResourceManager.GetString("SndUriHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address:.
        /// </summary>
        public static string StreetAddrHdr {
            get {
                return ResourceManager.GetString("StreetAddrHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Addresses:.
        /// </summary>
        public static string StreetAddrsHdr {
            get {
                return ResourceManager.GetString("StreetAddrsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribed.
        /// </summary>
        public static string subscribed {
            get {
                return ResourceManager.GetString("subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag arrived..
        /// </summary>
        public static string tagArrivedMsg {
            get {
                return ResourceManager.GetString("tagArrivedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag departed..
        /// </summary>
        public static string tagDepartedMsg {
            get {
                return ResourceManager.GetString("tagDepartedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories (tags):.
        /// </summary>
        public static string TagsHdr {
            get {
                return ResourceManager.GetString("TagsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone:.
        /// </summary>
        public static string TelHdr {
            get {
                return ResourceManager.GetString("TelHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string TextHdr {
            get {
                return ResourceManager.GetString("TextHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleHdr {
            get {
                return ResourceManager.GetString("TitleHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNF.
        /// </summary>
        public static string TNF {
            get {
                return ResourceManager.GetString("TNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Length:.
        /// </summary>
        public static string TypeLengthHdr {
            get {
                return ResourceManager.GetString("TypeLengthHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone:.
        /// </summary>
        public static string TzHdr {
            get {
                return ResourceManager.GetString("TzHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Identifier:.
        /// </summary>
        public static string UidHdr {
            get {
                return ResourceManager.GetString("UidHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Type.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type.
        /// </summary>
        public static string UnsupportedType {
            get {
                return ResourceManager.GetString("UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        public static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI:.
        /// </summary>
        public static string URIHdr {
            get {
                return ResourceManager.GetString("URIHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string UrlHdr {
            get {
                return ResourceManager.GetString("UrlHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF16.
        /// </summary>
        public static string UTF16 {
            get {
                return ResourceManager.GetString("UTF16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message data contains a UTF-16LE encoded string that is a URI..
        /// </summary>
        public static string UTF16LE_Msg {
            get {
                return ResourceManager.GetString("UTF16LE_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF8.
        /// </summary>
        public static string UTF8 {
            get {
                return ResourceManager.GetString("UTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCard Bytes:.
        /// </summary>
        public static string VcardBytesHdr {
            get {
                return ResourceManager.GetString("VcardBytesHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCard Data:.
        /// </summary>
        public static string vCardDataHdr {
            get {
                return ResourceManager.GetString("vCardDataHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCard Param:.
        /// </summary>
        public static string VcardParamHdr {
            get {
                return ResourceManager.GetString("VcardParamHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vCard Version:.
        /// </summary>
        public static string VcVersionHdr {
            get {
                return ResourceManager.GetString("VcVersionHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        public static string VoicePre {
            get {
                return ResourceManager.GetString("VoicePre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Forum Well Known Type:.
        /// </summary>
        public static string WellKnownTypeHdr {
            get {
                return ResourceManager.GetString("WellKnownTypeHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Address:.
        /// </summary>
        public static string WkAdrHdr {
            get {
                return ResourceManager.GetString("WkAdrHdr", resourceCulture);
            }
        }
    }
}
